redis:
  image: redis

timesource:
  image: springcloud/stream-module-launcher
  links:
    - redis
  environment:
    SPRING_REDIS_HOST: redis
    MODULES: org.springframework.cloud.stream.module:time-source:1.0.0.BUILD-SNAPSHOT
    SPRING_CLOUD_STREAM_BINDINGS_OUTPUT: ticktock

logsink:
  image: springcloud/stream-module-launcher
  links:
    - redis
  environment:
    SPRING_REDIS_HOST: redis
    MODULES: org.springframework.cloud.stream.module:log-sink:1.0.0.BUILD-SNAPSHOT
    SERVER_PORT: 8081
    SPRING_CLOUD_STREAM_BINDINGS_INPUT: ticktock
